


LIBNAME SEX 'L:\Sexual Satisfaction and Cognition\Sexual Satisfaction' ;
RUN;

PROC FREQ DATA = SEX.SEXLONG08032021;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =1;
TABLE   WNW CHARLSON_CAT CVDtotal_cat CURSMOKE ALC_CAT  ERECTILE_FX_DYS_B EDMED_ALT SUM_HYP COMMITTED;
RUN;



PROC MEANS DATA = SEX.SEXLONG08032021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =3;
VAR AGE NAS201TRAN TEDALL INCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;


PROC FREQ DATA = SEX.SEXLONG08032021;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =2;
TABLE   WNW CHARLSON_CAT CVDtotal_cat CURSMOKE ALC_CAT  ERECTILE_FX_DYS_B EDMED_ALT SUM_HYP COMMITTED;
RUN;



PROC MEANS DATA = SEX.SEXLONG08032021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =2;
VAR AGE NAS201TRAN TEDALL INCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;


PROC FREQ DATA = SEX.SEXLONG08032021;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =3;
TABLE   WNW CHARLSON_CAT CVDtotal_cat CURSMOKE ALC_CAT  ERECTILE_FX_DYS EDMED_ALT SUM_HYP COMMITTED;
RUN;



PROC MEANS DATA = SEX.SEXLONG08032021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 0 AND ERECTILE_FX_DYS_B = 0 AND WAVE =3;
VAR AGE NAS201TRAN TEDALL INCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;




TITLE "SEXUAL SATISFACTION PREDICTING MCI STEP 1";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1;
CLASS VETSAID CASE;
MODEL SEXSATTOTAL = AGE_C /DIST=NORM SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;


TITLE "SEXUAL SATISFACTION PREDICTING MCI STEP 1";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1;
CLASS VETSAID CASE;
MODEL NAS201TRAN(DESCENDING) = AGE_C
 /DIST=BINARY LINK=LOGIT SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;


*TABLE 2;
TITLE "PREDICTING SEXUAL SATISFACTION";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC CVDTOTAL  PAININTENMSSUM
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "AGE"   AGE_C 1 / CL;
ESTIMATE "WNW"   WNW 1 / CL;
ESTIMATE "INCOME"   INCOME  1 / CL;
ESTIMATE "NAS201TRAN1"   NAS201TRAN 1 / CL;
ESTIMATE "COMMITTED"  COMMITTED  1 / CL;
ESTIMATE "CESD"   CESD 1 / CL;
ESTIMATE "SF36PF_LONG"   SF36PF_LONG 1 / CL;
ESTIMATE "CVDTOTAL"  CVDTOTAL  1 / CL;
ESTIMATE "CHARLSON"   CHARLSON_NOHYP 1 / CL;
ESTIMATE "ALC_CAT"   ALC_CAT 1 / CL;
ESTIMATE "CURSMOKE"   CURSMOKE 1 / CL;
ESTIMATE "ATTSEX"   ATTSEX 1 / CL;
ESTIMATE "EDMED_ALT"   EDMED_ALT 1 / CL;
ESTIMATE "SUM_HYP    "   SUM_HYP    1 / CL;
ESTIMATE "BP ERECTILE FUNCTION" ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
ESTIMATE "DURATION OF CHRONIC PAIN" PAININTENMSSUM 1 / CL;
RUN;




TITLE "PREDICTING ERECTILE FUNCTION";
PROC MIXED DATA= SEX.SEXLONG08192021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED
SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE CURSMOKE SEXSATTOTAL PAININTENMSSUM
EDMED_ALT SUM_HYP
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "AGE"   AGE_C 1 / CL;
ESTIMATE "WNW"   WNW 1 / CL;
ESTIMATE "INCOME"   INCOME  1 / CL;
ESTIMATE "NAS201TRAN1"   NAS201TRAN 1 / CL;
ESTIMATE "COMMITTED"  COMMITTED  1 / CL;
*ESTIMATE "CESD"   CESD 1 / CL;
ESTIMATE "SF36PF_LONG"   SF36PF_LONG 1 / CL;
ESTIMATE "CVDTOTAL"  CVDTOTAL  1 / CL;
ESTIMATE "CHARLSON"   CHARLSON_NOHYP 1 / CL;
ESTIMATE "ALC_CAT"   ALC_CAT 1 / CL;
ESTIMATE "CURSMOKE"   CURSMOKE 1 / CL;
*ESTIMATE "ATTSEX"   ATTSEX 1 / CL;
ESTIMATE "EDMED_ALT"   EDMED_ALT 1 / CL;
ESTIMATE "SUM_HYP    "   SUM_HYP    1 / CL;
ESTIMATE "DURATION OF CHRONIC PAIN" PAININTENMSSUM 1 / CL;
RUN;


TITLE "PREDICTING ERECTILE FUNCTION";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE   CPmms_Inten
EDMED_ALT SUM_HYP
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "AGE"   AGE_C 1 / CL;
ESTIMATE "WNW"   WNW 1 / CL;
ESTIMATE "INCOME"   INCOME  1 / CL;
ESTIMATE "NAS201TRAN1"   NAS201TRAN 1 / CL;
ESTIMATE "COMMITTED"  COMMITTED  1 / CL;
ESTIMATE "CESD"   CESD 1 / CL;
ESTIMATE "SF36PF_LONG"   SF36PF_LONG 1 / CL;
ESTIMATE "CVDTOTAL"  CVDTOTAL 1 / CL;
ESTIMATE "CHARLSON"   CHARLSON_NOHYP 1 / CL;
ESTIMATE "ALC_CAT"   ALC_CAT 1 / CL;
ESTIMATE "CURSMOKE"   CURSMOKE 1 / CL;
ESTIMATE "ATTSEX"   ATTSEX 1 / CL;
ESTIMATE "EDMED_ALT"   EDMED_ALT 1 / CL;
ESTIMATE "SUM_HYP    "   SUM_HYP    1 / CL;
RUN;

TITLE "PREDICTING ERECTILE FUNCTION";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL ERECTILE_FX = AGE_C  WNW INCOME  NAS201TRAN COMMITTED
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC CPmms_Inten
EDMED_ALT SUM_HYP
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=AR(1);
ESTIMATE "AGE"   AGE_C 1 / CL;
ESTIMATE "WNW"   WNW 1 / CL;
ESTIMATE "INCOME"   INCOME  1 / CL;
ESTIMATE "NAS201TRAN1"   NAS201TRAN 1 / CL;
ESTIMATE "COMMITTED"  COMMITTED  1 / CL;
ESTIMATE "CESD"   CESD 1 / CL;
ESTIMATE "SF36PF_LONG"   SF36PF_LONG 1 / CL;
ESTIMATE "CVDTOTAL"  CVDTOTAL  1 / CL;
ESTIMATE "CHARLSON"   CHARLSON_NOHYP 1 / CL;
ESTIMATE "ALC_CAT"   ALC_CAT 1 / CL;
ESTIMATE "CURSMOKE"   CURSMOKE 1 / CL;
ESTIMATE "ATTSEX"   ATTSEX 1 / CL;
ESTIMATE "EDMED_ALT"   EDMED_ALT 1 / CL;
ESTIMATE "SUM_HYP    "   SUM_HYP    1 / CL;
RUN;


DATA SEX.SEXLONG08032021;
SET SEX.SEXLONG08032021;
CVDTOTALNEW = .;
CVDTOTALNEW = CVDTOTAL-SUM_HYP;
RUN;

PROC SORT DATA = SEX.SEXLONG08032021;
BY VETSAID;
RUN;

PROC SORT DATA = SEX.WAVESCOMPLETED;
BY VETSAID;
RUN;


DATA SEX.SEXLONG08192021;
MERGE SEX.SEXLONG08032021 SEX.WAVESCOMPLETED;
BY VETSAID;
RUN;






*TABLE 3;

*Sexual Satisfaction;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1;
CLASS VETSAID CASE;
MODEL C= AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC EDYN2_SUM SEXSATTOTAL_BPC
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;



*TABLE 3;

*Sexual Satisfaction;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC EDYN2_SUM SEXSATTOTAL_BPC  SPEED_B
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 4.06 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC
 ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC SPEED_B
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE
ATTSEX EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;

RUN;




*Erectile Function;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC|SEXSATTOTAL_BPC
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  speed = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


*****************************************;
COMMONEF
*****************************************;
*Sexual Satisfaction;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC
 ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML ;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC EF_B
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE
ATTSEX EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;

RUN;




*Erectile Function;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC EF_B
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;





*****************************************;
**MEMORY;
*****************************************;
*Sexual Satisfaction;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC A7_LONG
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC
 ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_BGMC SEXSATTOTAL_BPC MEMORY_B
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE
ATTSEX EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP SEXUAL SATIFACTION"   SEXSATTOTAL_BGMC 1 / CL;
ESTIMATE "WP SEXUAL SATIFACTION"   SEXSATTOTAL_BPC 1 / CL;
RUN;




*Erectile Function;
TITLE "ERECTILE FUNCTION AND SPEED - STEP 1 DEMOGRAPHIC ADJUSTMENT";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;

TITLE "ERECTILE FUNCTION AND SPEED - STEP 2 ADJUSTMENT FOR SEXUAL CHARACTERISTICS";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 ;
CLASS VETSAID CASE;
MODEL MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC
ATTSEX /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_GMC ERECTILE_FX_BPC MEMORY_B
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;




*SEXUAL FUNCTION;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXFUNCTION_BGMC SEXFUNCTION_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXFUNCTION_BGMC SEXFUNCTION_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;



TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  SPEED = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXFUNCTION_BGMC SEXFUNCTION_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;





*ERECTILE DYSFUNCTION;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_DYS_B
ERECTILE_FX_DYS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_DYS_B
ERECTILE_FX_DYS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;



TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  SPEED = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  ERECTILE_FX_DYS_B
ERECTILE_FX_DYS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;





*SEXUAL DISSATISFACTION;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  MEMORY = AGE_C  WNW INCOME  NAS201TRAN COMMITTED SEXSATTOTAL_DIS_B
SEXSATTOTAL_DIS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;


TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_DIS_B
SEXSATTOTAL_DIS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;



TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  SPEED = AGE_C  WNW INCOME  NAS201TRAN COMMITTED SEXSATTOTAL_DIS_B
SEXSATTOTAL_DIS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;





TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  COMMONEF = AGE_C  WNW INCOME  NAS201TRAN COMMITTED  SEXSATTOTAL_DIS_B
SEXSATTOTAL_DIS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;



TITLE "ERECTILE FUNCTION AND SPEED - STEP 3 ADJUSTMENT FOR HEALTH AND MEDICATION USE";
PROC MIXED DATA= SEX.SEXLONG08032021 NOCLPRINT COVTEST METHOD = ML;
WHERE MCICAT_B = 0 AND SEXSAT_VALID > 1 AND ERECTILE_FX_VALID > 1 and ERECTILE_FX_DYS_B =0;
CLASS VETSAID CASE;
MODEL  SPEED = AGE_C  WNW INCOME  NAS201TRAN COMMITTED SEXSATTOTAL_DIS_B
SEXSATTOTAL_DIS_BPC
CESD SF36PF_LONG  CVDTOTAL CHARLSON_NOHYP ALC_CAT CURSMOKE ATTSEX CURSMOKE
EDMED_ALT SUM_HYP    /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE=VC;
*ESTIMATE "BP ERECTILE FUNCTION"   ERECTILE_FX_GMC 1 / CL;
*ESTIMATE "WP  ERECTILE FUNCTION"   ERECTILE_FX_BPC 1 / CL;
RUN;




***************************************;
DESCRIPTIVES;
***************************************;


DATA SEX.SEXLONG07082021;
SET SEX.SEXLONG07072021;
MORBID = CHARLSON_NOHYP - CVDTOTAL;
CVDCAT = .;
IF CVDTOTAL = 0 THEN CVDCAT = 0;
IF CVDTOTAL = 1 THEN CVDCAT = 1;
IF CVDTOTAL >1 THEN CVDCAT = 2;

CHARLSONCAT = .;
IF CHARLSON_NOHYP = 0 THEN CHARLSONCAT= 0;
IF CHARLSON_NOHYP = 1 THEN CHARLSONCAT= 1;
IF CHARLSON_NOHYP >1 THEN CHARLSONCAT= 2;
RUN;



PROC FREQ DATA = SEX.SEXLONG07082021;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=1;
TABLE WNW COMMITTED SEXSATTOTAL_CI ERECTILEFX_CI SPEED_CI COMMONEF_CI MEMORY_CI
CVDCAT CHARLSONCAT CURSMOKE ALC_CAT EDMED_ALT SUM_HYP    ;
RUN;





PROC FREQ DATA = SEX.SEXLONG07082021;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=2;
TABLE WNW COMMITTED SEXSATTOTAL_CI ERECTILEFX_CI SPEED_CI COMMONEF_CI MEMORY_CI
CVDCAT CHARLSONCAT CURSMOKE ALC_CAT EDMED_ALT SUM_HYP    ;
RUN;




PROC FREQ DATA = SEX.SEXLONG07082021;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=3;
TABLE WNW COMMITTED SEXSATTOTAL_CI ERECTILEFX_CI SPEED_CI COMMONEF_CI MEMORY_CI
CVDCAT CHARLSONCAT CURSMOKE ALC_CAT EDMED_ALT SUM_HYP    ;
RUN;




PROC FREQ DATA = SEX.SEXLONG07072021;
WHERE MCICAT_B = 0 AND WAVE=2;
TABLE SEXSAT_VALID ERECTILE_FX_VALID;

RUN;

DATA SEX.SEXLONG07072021;
SET SEX.SEXLONG07072021;
SEX_CAT = .;
IF SEXSATTOTAL_BPC < 0 THEN SEX_CAT = -1;
IF SEXSATTOTAL_BPC = 0 THEN SEX_CAT = 0;
IF SEXSATTOTAL_BPC > 0 THEN SEX_CAT = 1;
EF_CAT = .;
IF ERECTILE_FX_BPC < 0 THEN EF_CAT = -1;
IF ERECTILE_FX_BPC = 0 THEN EF_CAT = 0;
IF ERECTILE_FX_BPC > 0 THEN EF_CAT = 1;
RUN;


PROC FREQ DATA = SEX.SEXLONG07072021;
WHERE MCICAT_B = 0 AND WAVE=3;
TABLE SEX_CAT EF_CAT;
RUN;



PROC MEANS DATA = SEX.SEXLONG07082021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=2;
VAR AGE NAS201TRANINCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;



PROC MEANS DATA = SEX.SEXLONG07082021 MEAN STDDEV MIN MAX N P25;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1  AND WAVE>1;
VAR AGE NAS201TRANINCOME SEXSATTOTAL_BPC ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;






PROC MEANS DATA = SEX.SEXLONG07082021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=2;
VAR AGE NAS201TRANINCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;



PROC MEANS DATA = SEX.SEXLONG07082021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0  AND SEXSATTOTAL NE . AND SEXSAT_VALID > 1 AND WAVE=3;
VAR AGE NAS201TRANINCOME SEXSATTOTAL SEXSATTOTAL_BPC ERECTILE_FX ERECTILE_FX_BPC ATTSEX SPEED COMMONEF MEMORY
CESD SF36PF_LONG BMI;
RUN;







PROC MEANS DATA = SEX.SEXLONG08032021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 1 AND SEXSAT_VALID > 1 AND WAVE=2;
VAR SEXSATTOTAL ERECTILE_FX ERECTILE_FX_GMC ERECTILE_FX_BPC;
RUN;


PROC MEANS DATA = SEX.SEXLONG08032021 MEAN STDDEV MIN MAX N;
WHERE MCICAT_B = 0 AND WAVE=2;
VAR  SEXSAT_VALID SEXSATTOTAL ERECTILE_FX ERECTILE_FX_GMC ERECTILE_FX_BPC;
RUN;





PROC MEANS DATA = SEX.SEXLONG08032021 N MEAN STDDEV MIN MAX ;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 2 AND SEXSAT_VALID > 2 AND WAVE=2;
VAR SEXSAT_VALID ERECTILE_FX_GMC ERECTILE_FX_BPC;
RUN;


PROC MEANS DATA = SEX.SEXLONG08032021 N MEAN STDDEV MIN MAX ;
WHERE MCICAT_B = 0 AND ERECTILE_FX_VALID > 2 AND SEXSAT_VALID > 2 AND WAVE=3;
VAR SEXSAT_VALID ERECTILE_FX_GMC ERECTILE_FX_BPC;
RUN;

















*Pain Intensity;


TITLE "Persistent pain Predicting Executive Function";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL COMMONEF = AGE_C|CPms_Inten_V3 CPmms_Inten_V3   WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;



TITLE "SEXUAL SATISFACTION PREDICTING MCI";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL WORK_MEM = AGE_C|CPms_Inten_V3 AGE_C|CPmms_Inten_V3  WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;




TITLE "SEXUAL SATISFACTION PREDICTING MCI";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL SPEED = AGE_C|CPms_Inten_V3  WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;



TITLE "SEXUAL SATISFACTION PREDICTING MCI";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL MEMORY = AGE_C|CPms_Inten_V3  WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;


TITLE "SEXUAL SATISFACTION PREDICTING MCI";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL VisSpat= AGE_C|CPms_Inten_V3  WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;


TITLE "SEXUAL SATISFACTION PREDICTING MCI";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL VisMem = AGE_C|CPms_Inten_V3  WNW INCOME  COMMITTED  NAS201TRAN
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;





*Pain Interference;


TITLE "Persistent pain Predicting Executive Function";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL COMMONEF = AGE_C CPms_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;

*p = .412;


TITLE "Persistent pain Predicting Executive Function";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL WORK_MEM = AGE_C CPms_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;
*p = .081;


TITLE "Persistent pain Predicting Executive Function";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL VISSPAT = AGE_C CPms_Inter_V3   WNW INCOME  NAS201TRAN OPIOIDMED_CAT
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;


TITLE "Persistent Pain Interference Predicting Speed";
PROC GLIMMIX DATA=SEX.SEXLONG08032021 METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0;
CLASS VETSAID CASE SPEED_CI;
MODEL SPEED = AGE_C CPms_Inter_V3   WNW INCOME NAS201TRAN  OPIOIDMED_CAT
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
RUN;
*p = .424;







TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN EXECUTIVE FUNCTION";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE;
MODEL commonef = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT EF_B
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT NAS201TRAN  /SUB=VETSAID(CASE) TYPE = VC;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 15 / CL;

ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 15 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN WORKING MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL work_mem = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT  work_mem_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inten_V3 0 AGE_C 15 / CL;

ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inten_V3 1 AGE_C 15 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;



TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL memory = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT memory_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN PROCESSING SPEED";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL speed = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT speed_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN VISUOSPATIAL ABILITY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL VISSPAT = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT VISSPAT_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;



TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN VISUAL MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL VISMEM = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT VISMEM_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;



TITLE "PERSISENT PAIN INTENSITY PREDICTING DECLINE IN FLUENCY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL fluency = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT fluency_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN SEMANTIC FLUENCY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL SEMANTIC_FLU = AGE_C CPms_Inten_V3 CPmild_Inten_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT SEMANTIC_FLU_V1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inten_V3" CPmild_Inten_V3 1 / CL;
ESTIMATE "CPms_Inten_V3" CPms_Inten_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN EXECUTIVE FUNCTION";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL commonef = AGE_C CPms_Inter_V3 CPmild_InteR_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT EF_b
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 15 / CL;

ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 15 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN WORKING MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave>1;
CLASS VETSAID CASE SPEED_CI;
MODEL work_mem = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT work_mem_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3 NONE " INTERCEPT 1 CPms_Inter_V3 0 AGE_C 15 / CL;

ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 1 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 2 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 3 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 4 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 5 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 6 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 7 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 8 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 9 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 10 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 11 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 12 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 13 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 14 / CL;
ESTIMATE "CPms_Inten_V3" INTERCEPT 1 CPms_Inter_V3 1 AGE_C 15 / CL;
RUN;


TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL memory = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT memory_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN PROCESSING SPEED";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL speed = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT speed_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN FLUENCY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL fluency = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT fluency_v1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;



TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN VISUOSPATIAL ABILITY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL VISSPAT = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT VISSPAT_V1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;



TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN VISUAL MEMORY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL VISMEM = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT VISMEM_V1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;




TITLE "PERSISENT PAIN INTERFERENCE PREDICTING DECLINE IN SEMANTIC FLUENCY";
PROC GLIMMIX DATA=SEX.painpaper METHOD= LAPLACE NOCLPRINT NOITPRINT;
WHERE MCICAT_B = 0 AND EXCLUDE = 0 and wave > 1;
CLASS VETSAID CASE SPEED_CI;
MODEL SEMANTIC_FLU = AGE_C CPms_Inter_V3 CPmild_Inter_V3  WNW INCOME  NAS201TRAN OPIOIDMED_CAT SEMANTIC_FLU_V1
CESD CHARLSON ALC_CAT CURSMOKE
 /DIST=NOR SOLUTION DDFM = BW;
RANDOM INTERCEPT/SUB=VETSAID(CASE) TYPE = UN;
ESTIMATE "CPmild_Inter_V3" CPmild_Inter_V3 1 / CL;
ESTIMATE "CPms_Inter_V3" CPms_Inter_V3 1 / CL;
ESTIMATE "OPIOIDMED_CAT" OPIOIDMED_CAT 1 / CL;
RUN;
